# These requests can be used with VSCode REST Client plugin.

# Use login to get an OAuth2 token, then use it in the authorization header. 

# Settings (set in VSCode settings.json file or uncomment and set below).
# Example settings.json:
#{
#    "rest-client.environmentVariables": {
#        "local": {
#            "baseUrl": "http://localhost/api/v1",
#            "clientId": "12345678-abcd-1234-abcd-1234567890ab",
#            "clientSecret": "23456789-abcd-1234-abcd-1234567890ab" 
#        }
#    }
#}
#
# Make sure to activate the correct environment in VSCode (lower right corner).
#
#@baseUrl = "http://localhost/api/v1"
#@clientId = "12345678-1234..."
#@clientSecret = "12345678-1234..."

# OAuth2 token, retrieved from login request:
@token = {{login.response.body.access_token}}

### 
# @name login
POST {{baseUrl}}/oauth/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{clientId}}&client_secret={{clientSecret}}&scope=

###
# @name item_statuses
GET {{baseUrl}}/contrib/kohasuomi/availability/biblios/2/search HTTP/1.1
Authorization: Bearer {{token}}

###
# @name hold_availability
GET {{baseUrl}}/contrib/kohasuomi/availability/biblios/2/hold?patron_id=57&include_found_in_hold_queue=0 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name item_hold_availability
GET {{baseUrl}}/contrib/kohasuomi/availability/items/30/hold?patron_id=57&include_found_in_hold_queue=1 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name hold_availability_with_patron_ignored
GET {{baseUrl}}/contrib/kohasuomi/availability/biblios/2/hold?patron_id=57&ignore_patron_holds=1 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name patron_information
GET {{baseUrl}}/patrons/57 HTTP/1.1
Authorization: Bearer {{token}}
X-Koha-Embed: extended_attributes

###
# @name patron_status
GET {{baseUrl}}/contrib/kohasuomi/patrons/57?query_messaging_preferences=1 HTTP/1.1
Authorization: Bearer {{token}}
X-Koha-Embed: extended_attributes

###
# @name patron_article_requests
GET {{baseUrl}}/contrib/kohasuomi/patrons/57/articlerequests HTTP/1.1
Authorization: Bearer {{token}}

###
# @name patron_article_requests_canceled
GET {{baseUrl}}/contrib/kohasuomi/patrons/57/articlerequests?status=CANCELED HTTP/1.1
Authorization: Bearer {{token}}

###
# @name patron_article_requests_page
GET {{baseUrl}}/contrib/kohasuomi/patrons/57/articlerequests?status=CANCELED&_page=2&_per_page=2 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name patron_checkouts
GET {{baseUrl}}/contrib/kohasuomi/patrons/57/checkouts?_order_by=%2Bdue_date&_page=1&_per_page=15 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name patron_checkouts_page
GET {{baseUrl}}/contrib/kohasuomi/patrons/306/checkouts?_page=2&_per_page=2 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name patron_anonymize
DELETE {{baseUrl}}/contrib/kohasuomi/patrons/1/checkouts/history HTTP/1.1
Authorization: Bearer {{token}}

###
# @name course_reserves
GET {{baseUrl}}/contrib/kohasuomi/coursereserves?_page=1 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name course_reserves_course_1
GET {{baseUrl}}/contrib/kohasuomi/coursereserves?course_id=1&_page=1 HTTP/1.1
Authorization: Bearer {{token}}

###
# @name items with strings
GET {{baseUrl}}/biblios/2/items
Authorization: Bearer {{token}}
x-koha-embed: +strings